import { Ingredient } from '@/types/Ingredient'

export const baseIngredients: Omit<Ingredient, 'id'>[] = [
    {
        name: 'jajka',
        type: 'amount',
        foodGroup: 'nabiał',
        kcal: 1.5,
        protein: 0.13,
        carbohydrates: 0.01,
        fat: 0.11,
        salt: 0.39,
    },
    {
        name: 'sól',
        type: 'mass',
        foodGroup: 'inne',
        kcal: 0.0,
        protein: 0.0,
        carbohydrates: 0.0,
        fat: 0.0,
        salt: 1.0,
        conversion: 0.7,
    },
    {
        name: 'cukier',
        type: 'mass',
        foodGroup: 'słodkie',
        kcal: 3.87,
        protein: 0.0,
        carbohydrates: 1.0,
        fat: 0.0,
        salt: 0.0,
        conversion: 0.85,
    },
    {
        name: 'wołowina',
        type: 'mass',
        foodGroup: 'mięso',
        kcal: 2.5,
        protein: 0.26,
        carbohydrates: 0.0,
        fat: 0.17,
        salt: 0.075,
        conversion: 1.0,
    },
    {
        name: 'masło',
        type: 'mass',
        foodGroup: 'nabiał',
        kcal: 7.17,
        protein: 0.0085,
        carbohydrates: 0.0006,
        fat: 0.81,
        salt: 0.02,
        conversion: 1.06,
    },
    {
        name: 'mleko',
        type: 'volume',
        foodGroup: 'nabiał',
        kcal: 0.42,
        protein: 0.034,
        carbohydrates: 0.05,
        fat: 0.01,
        salt: 0.1,
        conversion: 1.03,
    },
    {
        name: 'jabłko',
        type: 'amount',
        foodGroup: 'owoce',
        kcal: 0.52,
        protein: 0.0026,
        carbohydrates: 0.1381,
        fat: 0.0017,
        salt: 0.01,
    },
    {
        name: 'banan',
        type: 'amount',
        foodGroup: 'owoce',
        kcal: 0.89,
        protein: 0.0109,
        carbohydrates: 0.2284,
        fat: 0.0033,
        salt: 0.001,
    },
    {
        name: 'chleb biały',
        type: 'mass',
        foodGroup: 'pieczywo',
        kcal: 2.33,
        protein: 0.078,
        carbohydrates: 0.462,
        fat: 0.016,
        salt: 0.49,
        conversion: 0.45,
    },
    {
        name: 'ryż biały',
        type: 'mass',
        foodGroup: 'inne',
        kcal: 3.54,
        protein: 0.065,
        carbohydrates: 0.8,
        fat: 0.01,
        salt: 0.0,
        conversion: 0.85,
    },
    {
        name: 'ziemniaki',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.77,
        protein: 0.02,
        carbohydrates: 0.17,
        fat: 0.001,
        salt: 0.01,
        conversion: 1.0,
    },
    {
        name: 'marchew',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.41,
        protein: 0.0093,
        carbohydrates: 0.095,
        fat: 0.0024,
        salt: 0.07,
        conversion: 1.0,
    },
    {
        name: 'pomidor',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.18,
        protein: 0.009,
        carbohydrates: 0.039,
        fat: 0.002,
        salt: 0.005,
        conversion: 0.95,
    },
    {
        name: 'ser cheddar',
        type: 'mass',
        foodGroup: 'nabiał',
        kcal: 4.03,
        protein: 0.25,
        carbohydrates: 0.013,
        fat: 0.33,
        salt: 0.621,
        conversion: 0.9,
    },
    {
        name: 'jogurt naturalny',
        type: 'volume',
        foodGroup: 'nabiał',
        kcal: 0.61,
        protein: 0.059,
        carbohydrates: 0.056,
        fat: 0.012,
        salt: 0.05,
        conversion: 1.03,
    },
    {
        name: 'migdały',
        type: 'mass',
        foodGroup: 'orzechy',
        kcal: 5.93,
        protein: 0.21,
        carbohydrates: 0.22,
        fat: 0.49,
        salt: 0.001,
        conversion: 0.65,
    },
    {
        name: 'orzechy włoskie',
        type: 'mass',
        foodGroup: 'orzechy',
        kcal: 6.71,
        protein: 0.158,
        carbohydrates: 0.137,
        fat: 0.634,
        salt: 0.002,
        conversion: 0.6,
    },
    {
        name: 'awokado',
        type: 'amount',
        foodGroup: 'owoce',
        kcal: 1.88,
        protein: 0.026,
        carbohydrates: 0.015,
        fat: 0.181,
        salt: 0.007,
    },
    {
        name: 'czosnek',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 1.49,
        protein: 0.063,
        carbohydrates: 0.334,
        fat: 0.005,
        salt: 0.017,
        conversion: 1.0,
    },
    {
        name: 'cebula',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.4,
        protein: 0.011,
        carbohydrates: 0.093,
        fat: 0.001,
        salt: 0.004,
        conversion: 1.0,
    },
    {
        name: 'łosoś',
        type: 'mass',
        foodGroup: 'mięso',
        kcal: 2.08,
        protein: 0.2,
        carbohydrates: 0.0,
        fat: 0.13,
        salt: 0.059,
        conversion: 1.0,
    },
    {
        name: 'kurczak',
        type: 'mass',
        foodGroup: 'mięso',
        kcal: 1.65,
        protein: 0.31,
        carbohydrates: 0.0,
        fat: 0.037,
        salt: 0.07,
        conversion: 1.0,
    },
    {
        name: 'oliwa z oliwek',
        type: 'volume',
        foodGroup: 'tłuszcze',
        kcal: 8.84,
        protein: 0.0,
        carbohydrates: 0.0,
        fat: 1.0,
        salt: 0.0,
        conversion: 0.92,
    },
    {
        name: 'szpinak',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.23,
        protein: 0.029,
        carbohydrates: 0.037,
        fat: 0.003,
        salt: 0.02,
        conversion: 1.0,
    },
    {
        name: 'brokuły',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.34,
        protein: 0.029,
        carbohydrates: 0.067,
        fat: 0.003,
        salt: 0.04,
        conversion: 1.0,
    },
    {
        name: 'marakuja',
        type: 'amount',
        foodGroup: 'owoce',
        kcal: 3.4,
        protein: 0.04,
        carbohydrates: 0.89,
        fat: 0.19,
        salt: 0.03,
    },
    {
        name: 'truskawki',
        type: 'amount',
        foodGroup: 'owoce',
        kcal: 0.32,
        protein: 0.007,
        carbohydrates: 0.075,
        fat: 0.001,
        salt: 0.001,
    },
    {
        name: 'gruszka',
        type: 'amount',
        foodGroup: 'owoce',
        kcal: 0.57,
        protein: 0.007,
        carbohydrates: 0.15,
        fat: 0.002,
        salt: 0.001,
    },
    {
        name: 'śliwki',
        type: 'amount',
        foodGroup: 'owoce',
        kcal: 0.46,
        protein: 0.01,
        carbohydrates: 0.12,
        fat: 0.001,
        salt: 0.001,
    },
    {
        name: 'winogrona',
        type: 'amount',
        foodGroup: 'owoce',
        kcal: 0.69,
        protein: 0.007,
        carbohydrates: 0.18,
        fat: 0.002,
        salt: 0.002,
    },
    {
        name: 'maliny',
        type: 'amount',
        foodGroup: 'owoce',
        kcal: 0.52,
        protein: 0.012,
        carbohydrates: 0.12,
        fat: 0.003,
        salt: 0.003,
    },
    {
        name: 'arbuz',
        type: 'amount',
        foodGroup: 'owoce',
        kcal: 0.3,
        protein: 0.006,
        carbohydrates: 0.08,
        fat: 0.001,
        salt: 0.003,
    },
    {
        name: 'kapusta',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.25,
        protein: 0.015,
        carbohydrates: 0.06,
        fat: 0.003,
        salt: 0.03,
        conversion: 1.0,
    },
    {
        name: 'kalafior',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.25,
        protein: 0.02,
        carbohydrates: 0.05,
        fat: 0.003,
        salt: 0.01,
        conversion: 1.0,
    },
    {
        name: 'szparagi',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.2,
        protein: 0.022,
        carbohydrates: 0.04,
        fat: 0.002,
        salt: 0.02,
        conversion: 1.0,
    },
    {
        name: 'melon',
        type: 'amount',
        foodGroup: 'owoce',
        kcal: 0.34,
        protein: 0.009,
        carbohydrates: 0.085,
        fat: 0.003,
        salt: 0.001,
    },
    {
        name: 'kukurydza',
        type: 'mass',
        foodGroup: 'inne',
        kcal: 3.36,
        protein: 0.09,
        carbohydrates: 0.74,
        fat: 0.04,
        salt: 0.0,
        conversion: 0.9,
    },
    {
        name: 'dynia',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.26,
        protein: 0.01,
        carbohydrates: 0.07,
        fat: 0.004,
        salt: 0.03,
        conversion: 1.0,
    },
    {
        name: 'bakłażan',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.25,
        protein: 0.02,
        carbohydrates: 0.06,
        fat: 0.01,
        salt: 0.02,
        conversion: 1.0,
    },
    {
        name: 'kurkuma',
        type: 'mass',
        foodGroup: 'inne',
        kcal: 3.46,
        protein: 0.091,
        carbohydrates: 0.73,
        fat: 0.1,
        salt: 0.03,
        conversion: 0.4,
    },
    {
        name: 'miód',
        type: 'volume',
        foodGroup: 'inne',
        kcal: 3.04,
        protein: 0.03,
        carbohydrates: 0.82,
        fat: 0.0,
        salt: 0.01,
        conversion: 1.3,
    },
    {
        name: 'mięta',
        type: 'mass',
        foodGroup: 'inne',
        kcal: 2.93,
        protein: 0.07,
        carbohydrates: 0.56,
        fat: 0.09,
        salt: 0.02,
        conversion: 0.5,
    },
    {
        name: 'bazylii',
        type: 'mass',
        foodGroup: 'inne',
        kcal: 2.67,
        protein: 0.09,
        carbohydrates: 0.63,
        fat: 0.06,
        salt: 0.01,
        conversion: 0.5,
    },
    {
        name: 'pomidory suszone',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 3.19,
        protein: 0.13,
        carbohydrates: 0.69,
        fat: 0.03,
        salt: 0.01,
        conversion: 0.85,
    },
    {
        name: 'groszek',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.81,
        protein: 0.05,
        carbohydrates: 0.14,
        fat: 0.02,
        salt: 0.01,
        conversion: 1.0,
    },
    {
        name: 'ziarna słonecznika',
        type: 'mass',
        foodGroup: 'orzechy',
        kcal: 5.85,
        protein: 0.21,
        carbohydrates: 0.2,
        fat: 0.51,
        salt: 0.001,
        conversion: 0.65,
    },
    {
        name: 'marchewka',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.41,
        protein: 0.009,
        carbohydrates: 0.095,
        fat: 0.002,
        salt: 0.07,
        conversion: 1.0,
    },
    {
        name: 'feta',
        type: 'mass',
        foodGroup: 'nabiał',
        kcal: 2.74,
        protein: 0.14,
        carbohydrates: 0.04,
        fat: 0.21,
        salt: 0.68,
        conversion: 0.75,
    },
    {
        name: 'sardynki',
        type: 'mass',
        foodGroup: 'mięso',
        kcal: 1.73,
        protein: 0.22,
        carbohydrates: 0.0,
        fat: 0.1,
        salt: 0.25,
        conversion: 1.0,
    },
    {
        name: 'pstrąg',
        type: 'mass',
        foodGroup: 'mięso',
        kcal: 1.61,
        protein: 0.2,
        carbohydrates: 0.0,
        fat: 0.09,
        salt: 0.03,
        conversion: 1.0,
    },
    {
        name: 'krewetki',
        type: 'mass',
        foodGroup: 'mięso',
        kcal: 0.99,
        protein: 0.24,
        carbohydrates: 0.0,
        fat: 0.02,
        salt: 0.13,
        conversion: 1.0,
    },
    {
        name: 'kielbasa',
        type: 'mass',
        foodGroup: 'mięso',
        kcal: 3.33,
        protein: 0.21,
        carbohydrates: 0.03,
        fat: 0.28,
        salt: 0.92,
        conversion: 1.0,
    },
    {
        name: 'ser ricotta',
        type: 'mass',
        foodGroup: 'nabiał',
        kcal: 1.39,
        protein: 0.07,
        carbohydrates: 0.03,
        fat: 0.07,
        salt: 0.02,
        conversion: 1.0,
    },
    {
        name: 'ser mascarpone',
        type: 'mass',
        foodGroup: 'nabiał',
        kcal: 4.03,
        protein: 0.05,
        carbohydrates: 0.02,
        fat: 0.43,
        salt: 0.02,
        conversion: 0.9,
    },
    {
        name: 'pieczarki',
        type: 'mass',
        foodGroup: 'warzywa',
        kcal: 0.22,
        protein: 0.03,
        carbohydrates: 0.03,
        fat: 0.004,
        salt: 0.02,
        conversion: 1.0,
    },
    {
        name: 'czekolada gorzka',
        type: 'mass',
        foodGroup: 'słodkie',
        kcal: 5.46,
        protein: 0.06,
        carbohydrates: 0.46,
        fat: 0.36,
        salt: 0.02,
        conversion: 0.75,
    },
]
