name: Default development pipeline

on:
    push:
        branches-ignore:
            - main
    pull_request:
        branches:
            - main

env:
    NODE_VERSION: '22.14.0'

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install dependencies
              run: npm ci

            - name: Compile
              run: npm run build

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install dependencies
              run: npm ci

            - name: Run lint
              run: npm run lint

    format:
        name: Format
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Use Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ env.NODE_VERSION }}

            -   name: Install dependencies
                run: npm ci

            -   name: Run Format
                run: npm run format
